version: '3.3'

services:
  back:
    build: .
    image: vpn-bot
    container_name: telegram-vpn-bot
    ports:
      - "8080:8080"
    env_file:
      - ../../.env
    extra_hosts:
      - "outline:$OUTLINE_URI"
